name: smart-questionbank

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: qb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d qb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -lc "npm i && npx prisma generate && EXPORT_JOBS_WORKER_ENABLED=0 npm run start:dev"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    env_file:
      - .env
    command: bash -lc "npm i && npx prisma generate && npm run start:worker:dev"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
