import { randomUUID } from 'node:crypto';
import * as path from 'node:path';
import * as fs from 'node:fs/promises';
import * as bcrypt from 'bcrypt';
import { PrismaClient } from '@prisma/client';

function inferAdminDatabaseUrl() {
  const explicit = process.env.RLS_ADMIN_DATABASE_URL;
  if (explicit && explicit.trim()) return explicit;

  const raw = process.env.DATABASE_URL;
  if (!raw) return undefined;

  try {
    const url = new URL(raw);
    if (url.username && url.username !== 'postgres') {
      url.username = 'postgres';
      url.password = 'postgres';
    }
    return url.toString();
  } catch {
    return undefined;
  }
}

const prisma = new PrismaClient({
  datasources: {
    db: {
      url: inferAdminDatabaseUrl()
    }
  }
});

const DEMO_USER_ID = '10000000-0000-0000-0000-000000000001';
const DEMO_TENANT_ID = '20000000-0000-0000-0000-000000000001';
const DEMO_MEMBER_ID = '30000000-0000-0000-0000-000000000001';
const DEMO_CHAPTER_ID = '40000000-0000-0000-0000-000000000001';
const DEMO_TAG_GEOMETRY_ID = '50000000-0000-0000-0000-000000000001';
const DEMO_TAG_FUNCTION_ID = '50000000-0000-0000-0000-000000000002';
const DEMO_QUESTION_1_ID = '60000000-0000-0000-0000-000000000001';
const DEMO_QUESTION_2_ID = '60000000-0000-0000-0000-000000000002';
const DEMO_QUESTION_3_ID = '60000000-0000-0000-0000-000000000003';
const DEMO_LAYOUT_1_ID = '70000000-0000-0000-0000-000000000001';
const DEMO_LAYOUT_2_ID = '70000000-0000-0000-0000-000000000002';
const DEMO_LAYOUT_3_ID = '70000000-0000-0000-0000-000000000003';
const DEMO_DOCUMENT_1_ID = '80000000-0000-0000-0000-000000000001';
const DEMO_DOCUMENT_2_ID = '80000000-0000-0000-0000-000000000002';
const DEMO_ASSET_1_ID = '90000000-0000-0000-0000-000000000001';
const DEMO_EXPORT_1_ID = 'a0000000-0000-0000-0000-000000000001';
const DEMO_EXPORT_2_ID = 'a0000000-0000-0000-0000-000000000002';
const DEMO_EXPORT_3_ID = 'a0000000-0000-0000-0000-000000000003';

async function ensureDemoPdfFile() {
  const outputPath = path.resolve(process.cwd(), 'tmp/demo-export-doc1.pdf');
  const pdf = `%PDF-1.4
1 0 obj
<< /Type /Catalog /Pages 2 0 R >>
endobj
2 0 obj
<< /Type /Pages /Kids [3 0 R] /Count 1 >>
endobj
3 0 obj
<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>
endobj
4 0 obj
<< /Length 66 >>
stream
BT
/F1 18 Tf
40 92 Td
(ShiTi demo export ready) Tj
0 -28 Td
(Generated by prisma seed.) Tj
ET
endstream
endobj
5 0 obj
<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>
endobj
xref
0 6
0000000000 65535 f 
0000000010 00000 n 
0000000063 00000 n 
0000000122 00000 n 
0000000248 00000 n 
0000000364 00000 n 
trailer
<< /Size 6 /Root 1 0 R >>
startxref
434
%%EOF
`;

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, pdf, 'utf8');
  const stat = await fs.stat(outputPath);
  return { outputPath, size: stat.size };
}

async function main() {
  const ensureStage = async (code: string, name: string, order: number) => {
    const existing = await prisma.stage.findFirst({ where: { tenantId: null, code } });
    if (existing) {
      return prisma.stage.update({
        where: { id: existing.id },
        data: { name, order, isSystem: true }
      });
    }

    return prisma.stage.create({
      data: {
        id: randomUUID(),
        tenantId: null,
        code,
        name,
        order,
        isSystem: true
      }
    });
  };

  const ensureGrade = async (stageId: string, code: string, name: string, order: number) => {
    const existing = await prisma.grade.findFirst({ where: { tenantId: null, stageId, code } });
    if (existing) {
      return prisma.grade.update({
        where: { id: existing.id },
        data: { name, order, isSystem: true }
      });
    }

    return prisma.grade.create({
      data: {
        id: randomUUID(),
        tenantId: null,
        stageId,
        code,
        name,
        order,
        isSystem: true
      }
    });
  };

  const primaryStage = await ensureStage('primary', '小学', 10);
  const middleStage = await ensureStage('middle', '初中', 20);
  const highStage = await ensureStage('high', '高中', 30);
  const undergraduateStage = await ensureStage('undergraduate', '本科', 40);
  const postgraduateStage = await ensureStage('postgraduate', '考研', 50);
  const topUpStage = await ensureStage('top-up', '专升本', 60);
  const examStage = await ensureStage('exam', '考试', 70);

  for (let grade = 1; grade <= 6; grade += 1) {
    await ensureGrade(primaryStage.id, `p${grade}-up`, `${grade}年级上`, grade * 10);
    await ensureGrade(primaryStage.id, `p${grade}-down`, `${grade}年级下`, grade * 10 + 1);
  }

  for (let grade = 7; grade <= 9; grade += 1) {
    await ensureGrade(middleStage.id, `m${grade}-up`, `${grade}年级上`, grade * 10);
    await ensureGrade(middleStage.id, `m${grade}-down`, `${grade}年级下`, grade * 10 + 1);
  }

  await ensureGrade(highStage.id, 'g10', '高一', 100);
  await ensureGrade(highStage.id, 'g11', '高二', 110);
  await ensureGrade(highStage.id, 'g12', '高三', 120);
  await ensureGrade(examStage.id, 'zhongkao', '中考', 10);
  await ensureGrade(examStage.id, 'gaokao', '高考', 20);

  // System defaults (tenantId = null)
  const subjects = [
    '语文',
    '数学',
    '英语',
    '物理',
    '化学',
    '生物',
    '科学',
    '政治',
    '历史',
    '地理',
    '文综',
    '理综',
    '技术'
  ];

  for (const name of subjects) {
    const existing = await prisma.subject.findFirst({ where: { tenantId: null, name } });
    if (!existing) {
      await prisma.subject.create({ data: { tenantId: null, name, isSystem: true } });
    } else if (!existing.isSystem) {
      await prisma.subject.update({ where: { id: existing.id }, data: { isSystem: true } });
    }
  }

  const textbooks = ['浙教版', '人教版', '通用版'];
  for (const name of textbooks) {
    const existing = await prisma.textbook.findFirst({ where: { tenantId: null, name } });
    if (!existing) {
      await prisma.textbook.create({ data: { tenantId: null, name, isSystem: true } });
    } else if (!existing.isSystem) {
      await prisma.textbook.update({ where: { id: existing.id }, data: { isSystem: true } });
    }
  }

  // Optional: keep the old fixed-id subject for backwards compatibility with early tests.
  await prisma.subject.upsert({
    where: { id: '00000000-0000-0000-0000-000000000010' },
    update: { tenantId: null, name: 'math', isSystem: true },
    create: { id: '00000000-0000-0000-0000-000000000010', tenantId: null, name: 'math', isSystem: true }
  });

  const [mathSubject, zhejiangTextbook, middleGrade] = await Promise.all([
    prisma.subject.findFirst({ where: { tenantId: null, name: '数学' } }),
    prisma.textbook.findFirst({ where: { tenantId: null, name: '浙教版' } }),
    prisma.grade.findFirst({ where: { tenantId: null, code: 'm9-up' } }),
  ]);

  if (!mathSubject || !zhejiangTextbook || !middleGrade) {
    throw new Error('Missing system taxonomy rows; run prisma seed bootstrap first');
  }

  const passwordHash = await bcrypt.hash('demo-password', 10);
  await prisma.user.upsert({
    where: { id: DEMO_USER_ID },
    update: {
      username: 'teacher_demo',
      passwordHash,
    },
    create: {
      id: DEMO_USER_ID,
      username: 'teacher_demo',
      passwordHash,
    },
  });

  await prisma.tenant.upsert({
    where: { id: DEMO_TENANT_ID },
    update: {
      code: 'math-studio',
      name: '数学教研组',
    },
    create: {
      id: DEMO_TENANT_ID,
      code: 'math-studio',
      name: '数学教研组',
    },
  });

  await prisma.$transaction(async (tx) => {
    await tx.$executeRaw`SELECT set_config('app.tenant_id', ${DEMO_TENANT_ID}, true)`;

    await tx.tenantMember.upsert({
      where: {
        tenantId_userId: {
          tenantId: DEMO_TENANT_ID,
          userId: DEMO_USER_ID,
        }
      },
      update: {
        role: 'owner',
        status: 'active',
      },
      create: {
        tenantId: DEMO_TENANT_ID,
        id: DEMO_MEMBER_ID,
        userId: DEMO_USER_ID,
        role: 'owner',
        status: 'active',
      },
    });

    await tx.chapter.upsert({
      where: {
        tenantId_id: {
          tenantId: DEMO_TENANT_ID,
          id: DEMO_CHAPTER_ID,
        }
      },
      update: {
        textbookId: zhejiangTextbook.id,
        name: '相似三角形与函数综合',
        parentId: null,
      },
      create: {
        tenantId: DEMO_TENANT_ID,
        id: DEMO_CHAPTER_ID,
        textbookId: zhejiangTextbook.id,
        parentId: null,
        name: '相似三角形与函数综合',
      },
    });

    await tx.questionTag.upsert({
      where: {
        tenantId_id: {
          tenantId: DEMO_TENANT_ID,
          id: DEMO_TAG_GEOMETRY_ID,
        }
      },
      update: { name: '几何综合' },
      create: {
        tenantId: DEMO_TENANT_ID,
        id: DEMO_TAG_GEOMETRY_ID,
        name: '几何综合',
      },
    });

    await tx.questionTag.upsert({
      where: {
        tenantId_id: {
          tenantId: DEMO_TENANT_ID,
          id: DEMO_TAG_FUNCTION_ID,
        }
      },
      update: { name: '二次函数' },
      create: {
        tenantId: DEMO_TENANT_ID,
        id: DEMO_TAG_FUNCTION_ID,
        name: '二次函数',
      },
    });

    await tx.question.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_QUESTION_1_ID } },
    update: {
      type: 'single_choice',
      difficulty: 3,
      defaultScore: '5.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_QUESTION_1_ID,
      type: 'single_choice',
      difficulty: 3,
      defaultScore: '5.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    });

    await tx.questionContent.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_1_ID } },
    update: {
      stemBlocks: [
        { type: 'text', text: '如图，已知 △ABC 与 △DEF 相似，且 AB=6，DE=4，BC=9。求 EF 的长度。' },
        { type: 'text', text: '下列选项中，哪一个是正确结论？' },
      ],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_1_ID,
      stemBlocks: [
        { type: 'text', text: '如图，已知 △ABC 与 △DEF 相似，且 AB=6，DE=4，BC=9。求 EF 的长度。' },
        { type: 'text', text: '下列选项中，哪一个是正确结论？' },
      ],
    },
    });

    await tx.questionExplanation.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_1_ID } },
    update: {
      overviewBlocks: [{ type: 'text', text: '先列对应边比例，再由已知边求未知边。' }],
      stepsBlocks: [
        { type: 'text', text: '由相似可得 AB/DE = BC/EF。' },
        { type: 'latex', text: '\\\\frac{6}{4}=\\\\frac{9}{EF}' },
        { type: 'text', text: '解得 EF = 6。' },
      ],
      commentaryBlocks: [{ type: 'text', text: '这是课堂里最适合练比例转化的一道入门题。' }],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_1_ID,
      overviewBlocks: [{ type: 'text', text: '先列对应边比例，再由已知边求未知边。' }],
      stepsBlocks: [
        { type: 'text', text: '由相似可得 AB/DE = BC/EF。' },
        { type: 'latex', text: '\\\\frac{6}{4}=\\\\frac{9}{EF}' },
        { type: 'text', text: '解得 EF = 6。' },
      ],
      commentaryBlocks: [{ type: 'text', text: '这是课堂里最适合练比例转化的一道入门题。' }],
    },
    });

    await tx.questionSource.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_1_ID } },
    update: { year: 2025, month: 9, sourceText: '数学教研组周练' },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_1_ID,
      year: 2025,
      month: 9,
      sourceText: '数学教研组周练',
    },
    });

    await tx.questionAnswerChoice.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_1_ID } },
    update: {
      optionsBlocks: [
        [{ type: 'text', text: 'A. 4' }],
        [{ type: 'text', text: 'B. 5' }],
        [{ type: 'text', text: 'C. 6' }],
        [{ type: 'text', text: 'D. 8' }],
      ],
      correct: ['C'],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_1_ID,
      optionsBlocks: [
        [{ type: 'text', text: 'A. 4' }],
        [{ type: 'text', text: 'B. 5' }],
        [{ type: 'text', text: 'C. 6' }],
        [{ type: 'text', text: 'D. 8' }],
      ],
      correct: ['C'],
    },
    });

    await tx.question.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_QUESTION_2_ID } },
    update: {
      type: 'solution',
      difficulty: 4,
      defaultScore: '12.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_QUESTION_2_ID,
      type: 'solution',
      difficulty: 4,
      defaultScore: '12.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    });

    await tx.questionContent.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_2_ID } },
    update: {
      stemBlocks: [
        { type: 'text', text: '已知二次函数 y=x²-4x+3。' },
        { type: 'text', text: '求它的顶点坐标，并说明它与 x 轴的交点情况。' },
      ],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_2_ID,
      stemBlocks: [
        { type: 'text', text: '已知二次函数 y=x²-4x+3。' },
        { type: 'text', text: '求它的顶点坐标，并说明它与 x 轴的交点情况。' },
      ],
    },
    });

    await tx.questionExplanation.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_2_ID } },
    update: {
      overviewBlocks: [{ type: 'text', text: '配方后可同时得到顶点和零点信息。' }],
      stepsBlocks: [
        { type: 'latex', text: 'y=x^2-4x+3=(x-2)^2-1' },
        { type: 'text', text: '顶点坐标为 (2,-1)。' },
        { type: 'text', text: '令 y=0，解得 x=1 或 x=3。' },
      ],
      commentaryBlocks: [{ type: 'text', text: '这道题适合串联“顶点式”和“图像交点”两个基本动作。' }],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_2_ID,
      overviewBlocks: [{ type: 'text', text: '配方后可同时得到顶点和零点信息。' }],
      stepsBlocks: [
        { type: 'latex', text: 'y=x^2-4x+3=(x-2)^2-1' },
        { type: 'text', text: '顶点坐标为 (2,-1)。' },
        { type: 'text', text: '令 y=0，解得 x=1 或 x=3。' },
      ],
      commentaryBlocks: [{ type: 'text', text: '这道题适合串联“顶点式”和“图像交点”两个基本动作。' }],
    },
    });

    await tx.questionSource.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_2_ID } },
    update: { year: 2025, month: 10, sourceText: '九上函数专题卷' },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_2_ID,
      year: 2025,
      month: 10,
      sourceText: '九上函数专题卷',
    },
    });

    await tx.questionAnswerSolution.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_2_ID } },
    update: {
      finalAnswerLatex: '(2,-1);\\\\ x=1,3',
      referenceAnswerBlocks: [
        { type: 'text', text: '顶点为 (2,-1)，抛物线与 x 轴交于 (1,0)、(3,0)。' },
      ],
      scoringPoints: [
        '正确配方得到顶点式',
        '写出顶点坐标',
        '正确求出两个交点'
      ],
      scoringPointsBlocks: [
        { type: 'text', text: '1. 正确配方得到顶点式。' },
        { type: 'text', text: '2. 写出顶点坐标。' },
        { type: 'text', text: '3. 正确求出两个零点。' },
      ],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_2_ID,
      finalAnswerLatex: '(2,-1);\\\\ x=1,3',
      referenceAnswerBlocks: [
        { type: 'text', text: '顶点为 (2,-1)，抛物线与 x 轴交于 (1,0)、(3,0)。' },
      ],
      scoringPoints: [
        '正确配方得到顶点式',
        '写出顶点坐标',
        '正确求出两个交点'
      ],
      scoringPointsBlocks: [
        { type: 'text', text: '1. 正确配方得到顶点式。' },
        { type: 'text', text: '2. 写出顶点坐标。' },
        { type: 'text', text: '3. 正确求出两个零点。' },
      ],
    },
    });

    await tx.question.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_QUESTION_3_ID } },
    update: {
      type: 'fill_blank',
      difficulty: 2,
      defaultScore: '6.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_QUESTION_3_ID,
      type: 'fill_blank',
      difficulty: 2,
      defaultScore: '6.00',
      subjectId: mathSubject.id,
      ownerUserId: DEMO_USER_ID,
      visibility: 'tenant_shared',
    },
    });

    await tx.questionContent.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_3_ID } },
    update: {
      stemBlocks: [
        { type: 'text', text: '已知抛物线 y=(x-2)²-1 的顶点坐标是 ______。' },
      ],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_3_ID,
      stemBlocks: [
        { type: 'text', text: '已知抛物线 y=(x-2)²-1 的顶点坐标是 ______。' },
      ],
    },
    });

    await tx.questionExplanation.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_3_ID } },
    update: {
      overviewBlocks: [{ type: 'text', text: '顶点式 y=(x-h)²+k 的顶点是 (h,k)。' }],
      stepsBlocks: [
        { type: 'text', text: '对比 y=(x-h)²+k。' },
        { type: 'text', text: '可得 h=2, k=-1。' },
      ],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_3_ID,
      overviewBlocks: [{ type: 'text', text: '顶点式 y=(x-h)²+k 的顶点是 (h,k)。' }],
      stepsBlocks: [
        { type: 'text', text: '对比 y=(x-h)²+k。' },
        { type: 'text', text: '可得 h=2, k=-1。' },
      ],
    },
    });

    await tx.questionAnswerBlank.upsert({
    where: { tenantId_questionId: { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_3_ID } },
    update: {
      blanks: ['(2,-1)'],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      questionId: DEMO_QUESTION_3_ID,
      blanks: ['(2,-1)'],
    },
    });

  const questionIds = [DEMO_QUESTION_1_ID, DEMO_QUESTION_2_ID, DEMO_QUESTION_3_ID];
    await tx.questionTagging.deleteMany({ where: { tenantId: DEMO_TENANT_ID, questionId: { in: questionIds } } });
    await tx.questionStage.deleteMany({ where: { tenantId: DEMO_TENANT_ID, questionId: { in: questionIds } } });
    await tx.questionGrade.deleteMany({ where: { tenantId: DEMO_TENANT_ID, questionId: { in: questionIds } } });
    await tx.questionTextbook.deleteMany({ where: { tenantId: DEMO_TENANT_ID, questionId: { in: questionIds } } });
    await tx.questionChapter.deleteMany({ where: { tenantId: DEMO_TENANT_ID, questionId: { in: questionIds } } });

    await tx.questionTagging.createMany({
    data: [
      { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_1_ID, tagId: DEMO_TAG_GEOMETRY_ID },
      { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_2_ID, tagId: DEMO_TAG_FUNCTION_ID },
      { tenantId: DEMO_TENANT_ID, questionId: DEMO_QUESTION_3_ID, tagId: DEMO_TAG_FUNCTION_ID },
    ],
    });

    await tx.questionStage.createMany({
    data: questionIds.map((questionId) => ({
      tenantId: DEMO_TENANT_ID,
      questionId,
      stageId: middleStage.id,
    })),
    });

    await tx.questionGrade.createMany({
    data: questionIds.map((questionId) => ({
      tenantId: DEMO_TENANT_ID,
      questionId,
      gradeId: middleGrade.id,
    })),
    });

    await tx.questionTextbook.createMany({
    data: questionIds.map((questionId) => ({
      tenantId: DEMO_TENANT_ID,
      questionId,
      textbookId: zhejiangTextbook.id,
    })),
    });

    await tx.questionChapter.createMany({
    data: questionIds.map((questionId) => ({
      tenantId: DEMO_TENANT_ID,
      questionId,
      chapterId: DEMO_CHAPTER_ID,
    })),
    });

    await tx.layoutElement.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_LAYOUT_1_ID } },
    update: {
      blocks: [{ type: 'text', text: '学习目标：理解相似三角形的判定、比例转化和典型追问。' }],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_LAYOUT_1_ID,
      blocks: [{ type: 'text', text: '学习目标：理解相似三角形的判定、比例转化和典型追问。' }],
    },
    });

    await tx.layoutElement.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_LAYOUT_2_ID } },
    update: {
      blocks: [{ type: 'text', text: '课堂提问：为什么这一步先找对应边，而不是先找角？' }],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_LAYOUT_2_ID,
      blocks: [{ type: 'text', text: '课堂提问：为什么这一步先找对应边，而不是先找角？' }],
    },
    });

    await tx.layoutElement.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_LAYOUT_3_ID } },
    update: {
      blocks: [{ type: 'text', text: '课后整理：二次函数中顶点式、零点、最值三者之间的联系。' }],
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_LAYOUT_3_ID,
      blocks: [{ type: 'text', text: '课后整理：二次函数中顶点式、零点、最值三者之间的联系。' }],
    },
    });

    await tx.document.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_DOCUMENT_1_ID } },
    update: {
      kind: 'handout',
      name: '九上相似专题讲义',
      createdByUserId: DEMO_USER_ID,
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_DOCUMENT_1_ID,
      kind: 'handout',
      name: '九上相似专题讲义',
      createdByUserId: DEMO_USER_ID,
    },
    });

    await tx.document.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_DOCUMENT_2_ID } },
    update: {
      kind: 'paper',
      name: '二次函数周测卷',
      createdByUserId: DEMO_USER_ID,
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_DOCUMENT_2_ID,
      kind: 'paper',
      name: '二次函数周测卷',
      createdByUserId: DEMO_USER_ID,
    },
    });

    await tx.documentItem.deleteMany({
    where: {
      tenantId: DEMO_TENANT_ID,
      documentId: { in: [DEMO_DOCUMENT_1_ID, DEMO_DOCUMENT_2_ID] },
    },
    });

    await tx.documentItem.createMany({
    data: [
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000001',
        documentId: DEMO_DOCUMENT_1_ID,
        orderIndex: 0,
        itemType: 'layout_element',
        layoutElementId: DEMO_LAYOUT_1_ID,
      },
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000002',
        documentId: DEMO_DOCUMENT_1_ID,
        orderIndex: 1,
        itemType: 'question',
        questionId: DEMO_QUESTION_1_ID,
        scoreOverride: '5.00',
      },
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000003',
        documentId: DEMO_DOCUMENT_1_ID,
        orderIndex: 2,
        itemType: 'layout_element',
        layoutElementId: DEMO_LAYOUT_2_ID,
      },
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000004',
        documentId: DEMO_DOCUMENT_2_ID,
        orderIndex: 0,
        itemType: 'question',
        questionId: DEMO_QUESTION_2_ID,
        scoreOverride: '12.00',
      },
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000005',
        documentId: DEMO_DOCUMENT_2_ID,
        orderIndex: 1,
        itemType: 'question',
        questionId: DEMO_QUESTION_3_ID,
        scoreOverride: '6.00',
      },
      {
        tenantId: DEMO_TENANT_ID,
        id: 'b0000000-0000-0000-0000-000000000006',
        documentId: DEMO_DOCUMENT_2_ID,
        orderIndex: 2,
        itemType: 'layout_element',
        layoutElementId: DEMO_LAYOUT_3_ID,
      },
    ],
    });

    const exportFile = await ensureDemoPdfFile();
    await tx.asset.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_ASSET_1_ID } },
    update: {
      kind: 'export_result',
      originalFilename: 'demo-handout.pdf',
      storageKey: exportFile.outputPath,
      mime: 'application/pdf',
      size: exportFile.size,
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_ASSET_1_ID,
      kind: 'export_result',
      originalFilename: 'demo-handout.pdf',
      storageKey: exportFile.outputPath,
      mime: 'application/pdf',
      size: exportFile.size,
    },
    });

    await tx.exportJob.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_EXPORT_1_ID } },
    update: {
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_1_ID,
      status: 'succeeded',
      resultAssetId: DEMO_ASSET_1_ID,
      errorMessage: null,
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_EXPORT_1_ID,
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_1_ID,
      status: 'succeeded',
      resultAssetId: DEMO_ASSET_1_ID,
    },
    });

    await tx.exportJob.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_EXPORT_2_ID } },
    update: {
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_2_ID,
      status: 'pending',
      resultAssetId: null,
      errorMessage: null,
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_EXPORT_2_ID,
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_2_ID,
      status: 'pending',
    },
    });

    await tx.exportJob.upsert({
    where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: DEMO_EXPORT_3_ID } },
    update: {
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_2_ID,
      status: 'failed',
      resultAssetId: null,
      errorMessage: '演示失败任务：等待重试',
    },
    create: {
      tenantId: DEMO_TENANT_ID,
      id: DEMO_EXPORT_3_ID,
      kind: 'document_pdf',
      documentId: DEMO_DOCUMENT_2_ID,
      status: 'failed',
      errorMessage: '演示失败任务：等待重试',
    },
    });

    const studentProfiles = [
      {
        id: 'student-1',
        name: '林之涵',
        classId: 'class-1',
        className: '九年级尖子班',
        lessonId: 'lesson-1',
        documentId: DEMO_DOCUMENT_2_ID,
        documentName: '二次函数周测卷',
        gradeLabel: '初中 · 九年级下',
        subjectLabel: '数学',
        textbookLabel: '浙教版',
        trendLabel: '近期进步',
        habitTag: '订正及时',
        habitInsight: '课后会主动回看讲义边注，订正完成度高，适合逐步增加开放题表达训练。',
        followUpLevel: '常规关注',
        summary: '最近两次函数专题测试稳步提升，几何综合题仍然需要在证明链条上加强拆解。',
        scoreLabel: '92 / 100',
        historyTrendLabel: '86 → 89 → 92',
        wrongCountLabel: '6 道',
        wrongCount: 6,
        scoreRecords: [
          { label: '函数专题周测', score: 86, totalScore: 100, insight: '二次函数图像题失分较多，综合压轴题表达偏保守。' },
          { label: '相似综合复盘', score: 89, totalScore: 100, insight: '证明题结构更稳定，但开放题表达还可以再展开。' },
          { label: '二次函数压轴卷', score: 92, totalScore: 100, insight: '压轴题拆解明显进步，课堂讲解后复盘效果较好。' },
        ],
        feedbackRecords: [
          { label: '周测复盘课', status: '已回收', detail: '口头讲解完整度明显提升，下一轮可以加一点开放题追问。' },
          { label: '压轴题讲义回看', status: '跟进中', detail: '证明链条已稳定，但几何综合题仍需要单独拆一次已知/求证。' },
        ],
        wrongQuestionRecords: [
          { label: '二次函数压轴第 23 题', status: '已订正', followUp: '下轮口头讲解时复盘证明链条完整度。' },
          { label: '几何综合第 18 题', status: '待复盘', followUp: '需要补一次已知/求证拆解训练。' },
        ],
        highlights: [
          '相似三角形与二次函数综合题开始具备完整表达。',
          '课堂互动积极，课后讲义订正完成度高。',
          '可以逐步提高压轴题和开放题比重。',
        ],
        nextStep: '下一轮讲义里增加 2 道几何压轴题，并安排一次口头讲解复盘。',
      },
      {
        id: 'student-2',
        name: '徐若楠',
        classId: 'class-2',
        className: '九年级提高班',
        lessonId: 'lesson-2',
        documentId: DEMO_DOCUMENT_1_ID,
        documentName: '九上相似专题讲义',
        gradeLabel: '初中 · 九年级下',
        subjectLabel: '数学',
        textbookLabel: '浙教版',
        trendLabel: '波动明显',
        habitTag: '审题偏快',
        habitInsight: '课堂中容易直接下笔，跳过已知条件整理，适合在讲义里加入审题停顿框。',
        followUpLevel: '重点跟进',
        summary: '函数图像题失分较多，课堂作答时容易跳步骤，需要把题干拆解与审题节奏纳入跟进。',
        scoreLabel: '71 / 100',
        historyTrendLabel: '78 → 69 → 71',
        wrongCountLabel: '14 道',
        wrongCount: 14,
        scoreRecords: [
          { label: '函数图像小测', score: 78, totalScore: 100, insight: '基础代入题稳定，但表格与图像联动题停顿不足。' },
          { label: '讲义复盘测', score: 69, totalScore: 100, insight: '审题过快导致条件漏看，证明链条中断明显。' },
          { label: '课堂追问短测', score: 71, totalScore: 100, insight: '分步作答开始改善，但图像信息提取仍需专项跟进。' },
        ],
        feedbackRecords: [
          { label: '讲义推进课', status: '已回收', detail: '课堂追问能跟上，但审题停顿仍然不足，需要继续强化。' },
          { label: '短测回看', status: '待补录', detail: '等随堂短测完成后，把图像信息题的回收结果回写进学生画像。' },
        ],
        wrongQuestionRecords: [
          { label: '函数图像第 12 题', status: '待订正', followUp: '优先补图像与表格联动的已知条件整理。' },
          { label: '相似证明第 19 题', status: '已订正', followUp: '课堂中继续跟进口头复述是否稳定。' },
          { label: '开放探究第 24 题', status: '待讲解', followUp: '下节课安排一次分步板演和口头追问。' },
        ],
        highlights: [
          '函数图像题和表格信息题错误集中。',
          '错题订正完成，但口头复述仍不稳定。',
          '需要通过讲义中的“已知/求证”拆解框减缓审题节奏。',
        ],
        nextStep: '下节课前单独推送函数图像复盘讲义，并在课堂里安排一次分步板演。',
      },
      {
        id: 'student-3',
        name: '陈嘉言',
        classId: 'class-3',
        className: '高一物理培优班',
        lessonId: 'lesson-3',
        documentId: DEMO_DOCUMENT_1_ID,
        documentName: '九上相似专题讲义',
        gradeLabel: '高中 · 高一',
        subjectLabel: '物理',
        textbookLabel: '人教版',
        trendLabel: '稳定',
        habitTag: '错题回看',
        habitInsight: '习惯在课后回看错题与讲义边注，适合用个人工作区持续沉淀单人学习轨迹。',
        followUpLevel: '常规关注',
        summary: '力学计算题完成度稳定，个人工作区里重点跟踪的是错题回看的频次与课堂反馈衔接。',
        scoreLabel: '84 / 100',
        historyTrendLabel: '81 → 83 → 84',
        wrongCountLabel: '9 道',
        wrongCount: 9,
        scoreRecords: [
          { label: '力学模型起始测', score: 81, totalScore: 100, insight: '受力分析稳定，但图像信息转化速度偏慢。' },
          { label: '图像辨析短练', score: 83, totalScore: 100, insight: '图像题识别提升，讲义边注回看开始产生效果。' },
          { label: '课堂反馈复盘', score: 84, totalScore: 100, insight: '课堂反馈和错题回看已形成闭环，适合继续稳定推进。' },
        ],
        feedbackRecords: [
          { label: '模型导入课', status: '已回收', detail: '课堂互动稳定，图像辨析反馈已经能回写到个人工作区记录里。' },
          { label: '讲义边注复盘', status: '跟进中', detail: '下一轮重点确认边注回看是否能稳定转成课后任务。' },
        ],
        wrongQuestionRecords: [
          { label: '力学图像第 8 题', status: '待回看', followUp: '课后结合讲义边注再做一次图像辨析。' },
          { label: '模型转化第 15 题', status: '已复盘', followUp: '下次课堂继续观察物理量转化是否稳定。' },
        ],
        highlights: ['习惯在课后回看错题与讲义边注。', '需要强化图像信息提取和物理量转化。', '适合作为个人工作区样例，后续验证课堂反馈回流。'],
        nextStep: '将下一次课堂反馈与错题标签联动，验证个人工作区闭环。',
      },
    ] as const;

    const teachingClasses = [
      {
        id: 'class-1',
        name: '九年级尖子班',
        lessonId: 'lesson-1',
        documentId: DEMO_DOCUMENT_2_ID,
        focusStudentId: 'student-1',
        focusStudentName: '林之涵',
        stageLabel: '初中 · 冲刺组',
        teacherLabel: '主讲：陈老师',
        textbookLabel: '浙教版',
        focusLabel: '试卷跟进',
        activityLabel: '本周活跃',
        classSizeLabel: '26 人 · 小班精练',
        lessonFocusLabel: '复盘课',
        structureInsight: '班级规模适合精细追踪压轴题表达，可把课堂反馈直接回收进学生画像。',
        studentCount: 26,
        weeklyLessonCount: 3,
        latestDocLabel: '二次函数周测卷',
        assetLinks: [
          { label: '当前主资料', documentId: DEMO_DOCUMENT_2_ID, documentLabel: '二次函数周测卷', statusLabel: '试卷已定稿', detail: '作为本周复盘主资料，课堂里已经完成一次回看。' },
          { label: '讲义补充', documentId: DEMO_DOCUMENT_1_ID, documentLabel: '二次函数压轴题拆解讲义', statusLabel: '讲义待补', detail: '下一节复盘课需要把压轴题拆解讲义补进来，承接表达训练。' },
        ],
        memberTiers: [
          { label: '冲刺层', studentCount: 8, focus: '压轴题表达与证明链条稳定推进。' },
          { label: '稳固层', studentCount: 12, focus: '二次函数综合题保持正确率，继续补讲义拆解。' },
          { label: '跟进层', studentCount: 6, focus: '课堂复盘后重点跟进函数压轴题与错题订正。' },
        ],
        lessonTimeline: [
          { label: '周二 · 二次函数周测复盘', scheduleLabel: '已完成', statusLabel: '反馈已回收', focus: '重点回看压轴题的表达链条，并把复盘结果沉淀进学生画像。', lessonId: 'lesson-1', actionLabel: '查看复盘课详情' },
          { label: '周四 · 压轴题拆解讲义', scheduleLabel: '进行中', statusLabel: '资料待补', focus: '围绕讲义拆分压轴题模型，课堂里继续区分冲刺层和稳固层。', lessonId: 'lesson-1', actionLabel: '查看当前课堂详情' },
          { label: '周六 · 专题复盘课', scheduleLabel: '待开始', statusLabel: '课堂待排', focus: '把本周周测卷和讲义回看串到同一节专题课里，验证提分节奏。', lessonId: 'lesson-1', actionLabel: '查看待排课堂' },
        ],
        summary: '当前重点是周测卷复盘和压轴题讲解，班级对讲义中的板书提示响应较好。',
        highlights: ['本周安排 3 节课堂，2 份试卷回看，1 份讲义补充。', '需要关注中段学生在函数压轴题上的分层差异。', '最近导出资料以试卷为主，讲义需要补一次课堂版。'],
        nextStep: '先补一份“压轴题拆解讲义”，再串到周四的专题复盘课里。',
      },
      {
        id: 'class-2',
        name: '九年级提高班',
        lessonId: 'lesson-2',
        documentId: DEMO_DOCUMENT_1_ID,
        focusStudentId: 'student-2',
        focusStudentName: '徐若楠',
        stageLabel: '初中 · 提高组',
        teacherLabel: '主讲：沈老师',
        textbookLabel: '浙教版',
        focusLabel: '讲义整理',
        activityLabel: '本周活跃',
        classSizeLabel: '34 人 · 常规班型',
        lessonFocusLabel: '讲义推进',
        structureInsight: '班级人数偏多，讲义与课堂追问需要更强的分层结构，短测更适合作为课后回收。',
        studentCount: 34,
        weeklyLessonCount: 2,
        latestDocLabel: '相似三角形讲义',
        assetLinks: [
          { label: '当前主资料', documentId: DEMO_DOCUMENT_1_ID, documentLabel: '相似三角形讲义', statusLabel: '讲义已同步', detail: '当前课堂以讲义为主资料，课堂追问已经围绕讲义结构展开。' },
          { label: '短测资料', documentId: DEMO_DOCUMENT_2_ID, documentLabel: '相似三角形随堂短测', statusLabel: '试卷待补', detail: '下一轮课堂反馈需要通过短测资料回收并回写到班级分层。' },
        ],
        memberTiers: [
          { label: '提优层', studentCount: 9, focus: '保持讲义推进节奏，补短测承接开放题表达。' },
          { label: '主力层', studentCount: 17, focus: '围绕讲义例题和课堂追问建立稳定答题结构。' },
          { label: '跟进层', studentCount: 8, focus: '重点放慢审题节奏，先稳住图像和表格信息题。' },
        ],
        lessonTimeline: [
          { label: '周三 · 相似三角形讲义推进', scheduleLabel: '已完成', statusLabel: '讲义已同步', focus: '课堂例题和追问框反应较好，下一步需要补一轮短测回收。', lessonId: 'lesson-2', actionLabel: '查看讲义推进课' },
          { label: '周五 · 随堂短测', scheduleLabel: '待开始', statusLabel: '试卷待补', focus: '把讲义中的重点例题转成短测，区分主力层和跟进层的回收效果。', lessonId: 'lesson-2', actionLabel: '查看短测课堂' },
        ],
        summary: '班级目前更适合讲义驱动，课堂中对例题拆解和追问框的反馈较好。',
        highlights: ['最近一周以讲义整理和板书节奏优化为主。', '需要补一次随堂小测，把讲义反馈收回到题库复盘。', '班级人数较多，课堂任务要进一步分层。'],
        nextStep: '下节课前补一份短测卷，并按讲义段落安排分层互动。',
      },
      {
        id: 'class-3',
        name: '高一物理培优班',
        lessonId: 'lesson-3',
        documentId: DEMO_DOCUMENT_1_ID,
        focusStudentId: 'student-3',
        focusStudentName: '陈嘉言',
        stageLabel: '高中 · 培优组',
        teacherLabel: '主讲：周老师',
        textbookLabel: '人教版',
        focusLabel: '个人样例',
        activityLabel: '待推进',
        classSizeLabel: '18 人 · 培优班型',
        lessonFocusLabel: '模型拆解课',
        structureInsight: '适合作为物理培优样例，重点看讲义图示、课堂反馈和学生错题回看的闭环。',
        studentCount: 18,
        weeklyLessonCount: 1,
        latestDocLabel: '力学模型讲义',
        assetLinks: [
          { label: '当前主资料', documentId: DEMO_DOCUMENT_1_ID, documentLabel: '力学模型讲义', statusLabel: '讲义排版中', detail: '图示和板书提示还在微调，课堂前需要完成最终导出。' },
        ],
        memberTiers: [
          { label: '培优层', studentCount: 6, focus: '围绕力学模型与图像信息综合题继续提速。' },
          { label: '稳固层', studentCount: 8, focus: '保持受力分析稳定，补物理量转换表达。' },
          { label: '跟进层', studentCount: 4, focus: '先稳住图像辨析，再推进模型迁移。' },
        ],
        lessonTimeline: [
          { label: '下周一 · 力学模型拆解课', scheduleLabel: '待开始', statusLabel: '资料待排版', focus: '验证图像辨析段落和讲义图示是否足够清晰。', lessonId: 'lesson-3', actionLabel: '查看模型拆解课' },
        ],
        summary: '当前以物理培优样例为主，重点跟进图像辨析、模型识别和课后反馈沉淀。',
        highlights: ['课堂资料仍在排版。', '需要验证反馈能否回流到学生画像。', '适合作为个人工作区的高一物理样例链路。'],
        nextStep: '先完成讲义排版，再安排一轮图像辨析反馈回收。',
      },
    ] as const;

    const lessonSessions = [
      {
        id: 'lesson-1',
        title: '二次函数专题复盘课',
        classId: 'class-1',
        className: '九年级尖子班',
        focusStudentId: 'student-1',
        focusStudentName: '林之涵',
        teacherLabel: '主讲：陈老师',
        scheduleLabel: '周三 19:00 - 20:30',
        scheduleTag: '本周进行',
        classScopeLabel: '九年级尖子班',
        documentFocus: '二次函数周测卷',
        documentId: DEMO_DOCUMENT_2_ID,
        feedbackStatus: '待回收',
        followUpLabel: '补讲义',
        feedbackInsight: '本节课后要重点回收压轴题口头讲解、错题订正和课堂参与反馈，方便回写学生画像。',
        feedbackRecords: [
          { label: '口头讲解回收', status: '待回收', detail: '需要回收 5 名重点学生的压轴题口头讲解录入。' },
          { label: '错题订正', status: '部分完成', detail: '当前已收回一半订正稿，仍需补齐函数压轴题订正。' },
          { label: '课堂参与', status: '待整理', detail: '课堂追问记录已在教师侧完成，待沉淀到学生画像。' },
        ],
        assetRecords: [
          { label: '二次函数周测卷', kindLabel: '试卷', statusLabel: '已上课', detail: '本节课堂先用周测卷复盘，定位压轴题表达链条。', documentId: DEMO_DOCUMENT_2_ID, actionLabel: '查看试卷详情' },
          { label: '压轴题拆解讲义', kindLabel: '讲义', statusLabel: '待补充', detail: '需要补一页压轴题拆解讲义，承接课后复盘和下节专题课。', documentId: DEMO_DOCUMENT_2_ID, actionLabel: '查看讲义详情' },
        ],
        taskRecords: [
          { label: '回收 5 名重点学生口头讲解', ownerLabel: '课堂记录', statusLabel: '待处理', detail: '先补齐重点学生口头讲解，再回写到学生画像。', targetModule: 'students', targetRecordId: 'student-1', targetLabel: '林之涵', actionLabel: '查看学生详情' },
          { label: '整理函数压轴题订正稿', ownerLabel: '课后任务', statusLabel: '进行中', detail: '已收回一半订正稿，剩余部分需要在晚自习后补齐。', targetModule: 'documents', targetRecordId: DEMO_DOCUMENT_2_ID, targetLabel: '二次函数周测卷', actionLabel: '查看资料详情' },
        ],
        summary: '这节课会先复盘周测卷，再补一页压轴题拆解讲义，课后需要回收错题与口头讲解反馈。',
        highlights: ['主资料是试卷 + 补充讲义，课堂结构更像复盘课。', '课后要记录 5 名重点学生的压轴题表达问题。', '下节课前需把课堂反馈回写到学生画像和题库复盘。'],
        nextStep: '课后先收一轮错题反馈，再把讲义补充页挂到下节专题课。',
      },
      {
        id: 'lesson-2',
        title: '相似三角形讲义推进课',
        classId: 'class-2',
        className: '九年级提高班',
        focusStudentId: 'student-2',
        focusStudentName: '徐若楠',
        teacherLabel: '主讲：沈老师',
        scheduleLabel: '周四 18:30 - 20:00',
        scheduleTag: '本周进行',
        classScopeLabel: '九年级提高班',
        documentFocus: '相似三角形讲义',
        documentId: DEMO_DOCUMENT_1_ID,
        feedbackStatus: '已回收',
        followUpLabel: '短测跟进',
        feedbackInsight: '讲义反馈已收齐，下一轮重点是把课堂追问和课后短测结果重新沉淀到班级分层任务里。',
        feedbackRecords: [
          { label: '讲义反馈', status: '已收齐', detail: '课堂追问和板书提示反馈已经整理完成。' },
          { label: '短测结果', status: '待沉淀', detail: '分层短测已完成，待回写到班级分层任务。' },
          { label: '课堂追问', status: '已整理', detail: '高频卡点已提炼，可直接回流到下轮讲义。' },
        ],
        assetRecords: [
          { label: '相似三角形讲义', kindLabel: '讲义', statusLabel: '已使用', detail: '讲义版式和例题顺序已稳定，可直接承接短测回看。', documentId: DEMO_DOCUMENT_1_ID, actionLabel: '查看讲义详情' },
          { label: '相似三角形短测卷', kindLabel: '试卷', statusLabel: '待排版', detail: '短测卷还要补齐两道层级题，再进入周末班级复盘。', documentId: DEMO_DOCUMENT_2_ID, actionLabel: '查看试卷详情' },
        ],
        taskRecords: [
          { label: '沉淀讲义反馈到班级分层', ownerLabel: '班级跟进', statusLabel: '待处理', detail: '需要把课堂追问中的高频卡点拆回提优层和跟进层。', targetModule: 'classes', targetRecordId: 'class-2', targetLabel: '九年级提高班', actionLabel: '查看班级详情' },
          { label: '补周末短测卷', ownerLabel: '资料准备', statusLabel: '待开始', detail: '按本节课讲义重点补一份短测卷，验证分层效果。', targetModule: 'documents', targetRecordId: DEMO_DOCUMENT_1_ID, targetLabel: '相似三角形讲义', actionLabel: '查看资料详情' },
        ],
        summary: '本节以讲义推进为主，重点看例题拆解、课堂追问和课后短测之间的衔接。',
        highlights: ['讲义版式已经稳定，重点优化课堂追问节奏。', '反馈回收完成，可以开始沉淀短测题单。', '后续要把讲义反馈回流到班级分层任务里。'],
        nextStep: '补一份短测卷，并在周末班级复盘里对齐讲义重点段落。',
      },
      {
        id: 'lesson-3',
        title: '高一力学模型拆解课',
        classId: 'class-3',
        className: '高一物理培优班',
        focusStudentId: 'student-3',
        focusStudentName: '陈嘉言',
        teacherLabel: '主讲：周老师',
        scheduleLabel: '下周一 19:30 - 21:00',
        scheduleTag: '待准备',
        classScopeLabel: '高一物理培优班',
        documentFocus: '力学模型讲义',
        documentId: DEMO_DOCUMENT_1_ID,
        feedbackStatus: '待回收',
        followUpLabel: '资料待排版',
        feedbackInsight: '这节课的反馈重点是图像信息提取、模型识别和讲义图示是否足够清晰，适合先跑课堂样例。',
        feedbackRecords: [
          { label: '图像题反馈', status: '待回收', detail: '需要重点确认学生对图像辨析段落的理解情况。' },
          { label: '资料清晰度', status: '待确认', detail: '讲义图示还在排版，课堂后需确认图示是否足够清晰。' },
          { label: '模型识别', status: '样例跟进', detail: '本节先跑样例课堂，验证反馈能否回流到个人工作区。' },
        ],
        assetRecords: [
          { label: '力学模型讲义', kindLabel: '讲义', statusLabel: '排版中', detail: '图示和板书提示还在微调，课堂前需要完成最终导出。', documentId: DEMO_DOCUMENT_1_ID, actionLabel: '查看讲义详情' },
          { label: '图像辨析短练', kindLabel: '练习', statusLabel: '待创建', detail: '计划在课堂后段使用，帮助收图像信息提取反馈。', documentId: DEMO_DOCUMENT_1_ID, actionLabel: '查看资料详情' },
        ],
        taskRecords: [
          { label: '确认讲义图示清晰度', ownerLabel: '资料复核', statusLabel: '待确认', detail: '课堂后需要确认讲义图示是否足够清晰，决定是否追加重排版。', targetModule: 'documents', targetRecordId: DEMO_DOCUMENT_1_ID, targetLabel: '力学模型讲义', actionLabel: '查看资料详情' },
          { label: '回写课堂反馈', ownerLabel: '个人跟进', statusLabel: '待开始', detail: '验证课堂反馈是否能顺利回流到个人工作区学生画像。', targetModule: 'students', targetRecordId: 'student-3', targetLabel: '陈嘉言', actionLabel: '查看学生详情' },
        ],
        summary: '本节课围绕力学模型图示、图像辨析和反馈回收来跑一轮课堂样例。',
        highlights: ['讲义图示仍在排版。', '反馈重点是图像辨析与模型识别。', '需要验证反馈能否回流到学生画像。'],
        nextStep: '完成讲义排版后，先跑样例课堂，再回收反馈。',
      },
    ] as const;

    for (const student of studentProfiles) {
      await tx.studentProfile.upsert({
        where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: student.id } },
        update: student,
        create: { tenantId: DEMO_TENANT_ID, ...student },
      });
    }

    for (const classroom of teachingClasses) {
      await tx.teachingClass.upsert({
        where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: classroom.id } },
        update: classroom,
        create: { tenantId: DEMO_TENANT_ID, ...classroom },
      });
    }

    for (const lesson of lessonSessions) {
      await tx.lessonSession.upsert({
        where: { tenantId_id: { tenantId: DEMO_TENANT_ID, id: lesson.id } },
        update: lesson,
        create: { tenantId: DEMO_TENANT_ID, ...lesson },
      });
    }
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    // eslint-disable-next-line no-console
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
